/*********************
 * MIGRATION SCRIPT
 *********************/

CREATE DATABASE rmadridbasket;

/*SITE_CONFIGURATION*/

CREATE TABLE site_configuration (
	id int PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	value LONGTEXT NOT NULL,
	updated TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO site_configuration (name, value) VALUES ('title', 'rmadridbasket.es');
INSERT INTO site_configuration (name, value) VALUES ('description', 'Toda la actualidad sobre el Real Madrid de Baloncesto');
INSERT INTO site_configuration (name, value) VALUES ('keywords', 'real madrid, baloncesto, madrid, real, basket, basketball, acb, euroleague, euroliga, liga, endesa');
INSERT INTO site_configuration (name, value) VALUES ('author', 'rmadridbasket.es');
INSERT INTO site_configuration (name, value) VALUES ('copyright', 'rmadridbasket.es');


/*MENUS*/

CREATE TABLE menus (
	id int PRIMARY KEY AUTO_INCREMENT,
	menu VARCHAR(100) NOT NULL,
	item VARCHAR(100) NOT NULL,
	link VARCHAR(255) NOT NULL,
	item_order int NOT NULL, 
	updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO menus (menu, item, link, item_order) VALUES ('site-menu', 'Resultados', '#', 1);
INSERT INTO menus (menu, item, link, item_order) VALUES ('site-menu', 'Clasificaciones', '#', 2);
INSERT INTO menus (menu, item, link, item_order) VALUES ('site-menu', 'Plantilla', '#', 3);
INSERT INTO menus (menu, item, link, item_order) VALUES ('site-menu', 'Palmar&eacute;s', '#', 4);
INSERT INTO menus (menu, item, link, item_order) VALUES ('site-menu', 'Contacta', '#', 5);


/*NEWS*/

CREATE TABLE news (
	id int PRIMARY KEY AUTO_INCREMENT, 
	title VARCHAR(100) NOT NULL,
	content LONGTEXT NOT NULL,
	link VARCHAR(255), 
	source VARCHAR(75),
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO news (title, content, link, source) VALUES ('Noticia n&uacute;mero 1', 'Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/>', 'http://example.link.com', 'marca.com');
INSERT INTO news (title, content, link, source) VALUES ('Noticia n&uacute;mero 2', 'Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/>', 'http://example.link.com', 'as.com');
INSERT INTO news (title, content, link, source) VALUES ('Noticia n&uacute;mero 3', 'Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/>', 'http://example.link.com', 'mundodeportivo.es');
INSERT INTO news (title, content, link, source) VALUES ('Noticia n&uacute;mero 4', 'Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/>', 'http://example.link.com', 'euroleague.com');
INSERT INTO news (title, content, link, source) VALUES ('Noticia n&uacute;mero 5', 'Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/>', 'http://example.link.com', 'Carlos Sanchez Blas');
INSERT INTO news (title, content, link, source) VALUES ('Noticia n&uacute;mero 6', 'Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/>', 'http://example.link.com', 'encestando.es');
INSERT INTO news (title, content, link, source) VALUES ('Noticia n&uacute;mero 7', 'Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/> Este es un texto de ejemplo. <br/>. Aqu&iacute; hay un salto de linea, a ver como sale. Este texto es de ejemplo, y se repetira varias veces. <br/>', 'http://example.link.com', 'eurosport.es');



